name: eyebench
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - pandas=2.2.3
  - seaborn=0.13.2
  - matplotlib=3.10.1
  - numpy=2.2.4
  - transformers=4.47.1
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pyarrow=19.0.1
  - pyyaml=6.0.2
  - datasets=3.5.0
  - lightning=2.5.1
  - scikit-learn=1.6.1
  - pip=25.0.1
  - wordfreq=3.1.1
  - wandb=0.19.9
  - pre-commit=4.2.0
  - ruff=0.11.6
  - hydra-core=1.3.2
  - ipykernel=6.29.5
  - beartype=0.20.2
  - mypy=1.15.0
  - pandas-stubs=2.2.3
  - types-tqdm=4.67.0
  - py-xgboost=3.0.0
  - gpustat=1.1.1
  - ipywidgets=8.1.6
  - accelerate=1.5.2
  - typed-argument-parser=1.10.1
  - loguru=0.7.2
  - peft=0.15.2
  - spacy=3.8.5
  - pytorch-metric-learning=2.9.0
  - pip:
      - -e . # For development purposes
      - git+https://github.com/aeye-lab/pymovements.git@siqube-stack-pr
      - git+https://github.com/lacclab/text-metrics.git
      - en_core_web_sm@https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl
      - da_core_news_sm@https://github.com/explosion/spacy-models/releases/download/da_core_news_sm-3.8.0/da_core_news_sm-3.8.0-py3-none-any.whl
      - de_core_news_sm@https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.8.0/de_core_news_sm-3.8.0-py3-none-any.whl
      - juliacall