hyper_args:
  base_model: SupportVectorRegressorMLModel
  base_models:
  - AhnCNNModel
  - AhnRNNModel
  - BEyeLSTMModel
  - PLMASModel
  - MAGModel
  - PLMASFModel
  - PostFusionModel
  - Roberteye
  - Roberteye
  - Roberteye
  - SupportVectorRegressorMLModel
  - XGBoostRegressorMLModel
  - RandomForestRegressorMLModel
  - LinearRegressionRegressorMLModel
  - LinearRegressionRegressorMLModel
  - DummyRegressorMLModel
  data_task: CopCo_RCS
  data_tasks:
  - CopCo_RCS
  folds:
  - 0
  - 1
  - 2
  - 3
  gpu_count: 1
  model: SupportVectorRegressorMLArgs
  models:
  - AhnCNN
  - AhnRNN
  - BEyeLSTMArgs
  - PLMASArgs
  - MAG
  - PLMASfArgs
  - PostFusion
  - Roberta
  - RoberteyeFixation
  - RoberteyeWord
  - SupportVectorRegressorMLArgs
  - XGBoostRegressorMLArgs
  - RandomForestRegressorMLArgs
  - LinearRegressionArgs
  - LinearMeziereArgs
  - DummyRegressorMLArgs
  num_duplicates_per_gpu: 1
  run_cap: 1000
  search_algorithm: grid
  slurm_cpus: 10
  slurm_mailto: shubi@campus.technion.ac.il
  slurm_mem: 75G
  trainer: TrainerML
  trainers:
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerDL
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  - TrainerML
  wandb_entity: EyeRead
  wandb_project: CopCo_RCS_20251104
sweep_ids:
- 6wes3q0d
- g81r5bp6
- jdg4ox8m
- et8ltg5u
